package eu.kanade.domain.easteregg.lattice

/**
 * Generated by tools/lattice_forge.mjs — do not edit by hand.
 * Ciphertext only for board/rewards. FRAME + thresholds are required for Stage A
 * open-key derivation (scenario source of truth stays gitignored).
 */
internal object LatticeVaultData {
    const val VERSION = 555346607

    /** Opaque frame fragment for Stage A canonical (not a player-facing secret). */
    const val FRAME = "c4e19ab7d2f5083e"

    /** Latch thresholds for carriers in order: anime, manga, novel. */
    val THRESHOLDS = intArrayOf(1, 2, 3)

    val STAGE_A = LatticeStage(
        salt = "8NBsorOhdZ11in7IzqBHnA==",
        iv = "x6i/Fo/AZP4Ckwwt",
        check = "F1E1cVe4lENeGbKPuk2BruOqQD6wLMPDuYzuL2tmvXc=",
        data = "oMad3WBh7JMb8GRM13ZKp3NI1m/QroSRiJ7q6Tn9JbcxHS9cWcg8VrsUPIHugtPcbvVce41e6" +
            "KaLrB40FehX4I2EOP0z3esWiA1g8s+/zC4DkB8JwR4uSBmmn2steSyP5uG41s39fFK5pY0KfT" +
            "aFcTNroyebWHt8/hoenGuiE+HWPkqGPS/UbmpMjsS65YLK5A8ycZa5/DihWIevm9RGjRmjyMS" +
            "gf+/Ug8jI7av7vCamdlnGuNF9yOEBe4poOUSL9YJ1sdDratZnfrm58GhlDYH1CZSKm38E+mTu" +
            "Oiye3OZHzjnAKlc0ZItqw2k9E2Xq8rjR9PIHxlLgPJqy0WsguylOz9C+q927rLYsrM1noAvnp" +
            "QHJoUvCnukE+mzUxfWEUzR7UpgKyahAKqz5ZGoW3Yu/T6X00hLTBlrsmG+Yd3gZ6g0y7frlX8" +
            "d1VEB6YOVTpng=",
    )

    val STAGE_B = LatticeStage(
        salt = "2z2XnlZyVLhUjy+evIVtgA==",
        iv = "ZVJgtdTgnzq+yWkG",
        check = "gmn5Tso6HsPi57NT3nBbU9k225fbHHRYAR6ElMZ1Ejk=",
        data = "56jLt2ETSuZAXtCSGDD0JE5obGdkKKwimfZSQj5XVbV+iDzYZtvntoZ6OGSCCSo8xk8iy1" +
            "DzTp6L8G72kYHmrnrpPgDw5dosJsSxQYZfYHItZ+my31vmTDPmVDHWQPYtMM9PtN3bF1eS+RU" +
            "WpnGZ8FONjIjpVYFHal33vl3oSCx0z4Gd/1JDW6J/n5RE95Xwmthbl9WALrKFt2vwiukMDWMf" +
            "RVayjZUArbOxilHe",
    )
}
