package eu.kanade.domain.easteregg.lattice

/**
 * Generated by tools/lattice_forge.mjs — do not edit by hand.
 * Ciphertext only for board/rewards. FRAME + thresholds are required for Stage A
 * open-key derivation (scenario source of truth stays gitignored).
 */
internal object LatticeVaultData {
    const val VERSION = 611746306

    /** Opaque frame fragment for Stage A canonical (not a player-facing secret). */
    const val FRAME = "7f3a9c1e2b84d0f6"

    /** Latch thresholds for carriers in order: anime, manga, novel. */
    val THRESHOLDS = intArrayOf(1, 2, 3)

    val STAGE_A = LatticeStage(
        salt = "s6dDQY5TbpNFP/Nd0pVOZA==",
        iv = "WvtfoGM7Cayv7s0w",
        check = "sSYWN/mvBn5nKq58Rp9Nkvz8vqjBJYyteiOyd2WR3Ck=",
        data = "DDGHMTGqHmElkXeC9fcwVpVaGcE3Xq6aDRvA5lClpF/tHtT8zFkCTT4cYsVoPSTZOZvf4zqor3vf5k7KzAMJ6xPOh" +
            "kKgONlphJ/7/kt3NCsDCJqjQW119GdOp8Ftc/hN6ZpJW3mR5YcP/+SPJaoFEkXfEaWHPsDEyCfFj2KcRJ30QNJi02reYJIrraxvAWLD" +
            "H2gcJOkIi7xi6yi8MTmikU4PsHL9vHSiVQx8G02qlQ5UL0ibCVewkf1jcN8RUu/V6IL0xkxpXckUmolsHfq6RmYpUVwuW1ndf75hPy7I" +
            "pSiyPN3r4hL5tuGxrzdJB5KEOO+8Wj+zGl6kHsIIZm1u/rVVkDHkw29IJXX8oeRPKHGM6m1VUMvnBe7ZlhkkIttOZb8P7Ee1X3CbVkI" +
            "nvZjOCtiGG1w9VeK0XnIe/AAsX45XXm7WPHdFz1I6OdCovmzKgQzC3rxC6BCxQKTir+XohUsdY+p9syFUUsMq4gbMpsDZ3frxuggTp" +
            "JCkof2iFoXXbs8=",
    )

    val STAGE_B = LatticeStage(
        salt = "2pbsQSyyL29OdqNXScKPCA==",
        iv = "VzCAjYBE4M01F/Y7",
        check = "8XUVMMtHTtHIP3DloEE1gIRzw73uxgPzspscWQL4L/w=",
        data = "1JakhVQUfqM89rrhDZMpyLHDWcjyWYZNBqADfpNBs+7d7E2kO1tO7QQIPgF81i0O2Ms3YVL4uqjh60Had8uNn5ka0rmHPxBoLhVwV" +
            "uTp4FRg6z+7XrPxeIK8y74L921YZL6GF6ud/wi74HQBhJGpkVhwZc8ORMiSeDS+SXJCncJiV00L38dIpaWHIEewn80pBUwA/gv8dlh" +
            "K/JauNPCijkp/DLAHByxCMJe6WMin",
    )
}
