// Usage: node tools/lattice_forge.mjs <scenario.json> <outDir> <LatticeVaultData.kt path>
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import crypto from 'node:crypto';
import { canonicalCarriers, canonicalTopology } from './lattice_board.mjs';

const [scenarioPath, outDir, ktPath] = process.argv.slice(2);
if (!scenarioPath || !outDir || !ktPath) {
  console.error('Usage: node tools/lattice_forge.mjs <scenario.json> <outDir> <LatticeVaultData.kt>');
  process.exit(1);
}
const scenario = JSON.parse(readFileSync(scenarioPath, 'utf8'));
const ITER = 180000;
const pepper = String(scenario.pepper || '').trim();
if (!pepper || pepper.length < 8) {
  console.error('scenario.pepper required (min 8 chars) — keep only in gitignored scenario');
  process.exit(1);
}
const carriers = scenario.carriers;
if (!carriers || [carriers.a, carriers.m, carriers.n].some((v) => !Number.isInteger(v) || v < 1 || v > 9)) {
  console.error('scenario.carriers.{a,m,n} must be integers 1..9');
  process.exit(1);
}

function seal(canonical, plaintext) {
  const salt = crypto.randomBytes(16);
  const iv = crypto.randomBytes(12);
  const keyBuf = crypto.pbkdf2Sync(Buffer.from(canonical, 'utf8'), salt, ITER, 32, 'sha256');
  const check = crypto.createHash('sha256').update(keyBuf).digest();
  const c = crypto.createCipheriv('aes-256-gcm', keyBuf, iv);
  const ct = Buffer.concat([c.update(plaintext, 'utf8'), c.final(), c.getAuthTag()]);
  return {
    salt: salt.toString('base64'),
    iv: iv.toString('base64'),
    check: check.toString('base64'),
    data: ct.toString('base64'),
  };
}

const board = scenario.board;
const boardPlain = JSON.stringify({
  radius: board.radius,
  port: board.port,
  cells: board.cells.map((c) => ({ q: c.q, r: c.r, segment: c.segment, rotation: c.start })),
});
const stageA = seal(
  canonicalCarriers(carriers.a, carriers.m, carriers.n, pepper),
  boardPlain,
);
const solRot = new Map(board.cells.map((c) => [`${c.q},${c.r}`, c.solution]));
const stageB = seal(canonicalTopology(board, solRot), JSON.stringify(scenario.payload));

const VERSION = crypto.randomInt(1, 2 ** 30);
mkdirSync(outDir, { recursive: true });
writeFileSync(
  `${outDir}/lattice_vault.json`,
  JSON.stringify({ version: VERSION, pepper, carriers, stageA, stageB }, null, 2),
);

const stageKt = (s) =>
  `LatticeStage(\n        salt = "${s.salt}",\n        iv = "${s.iv}",\n        check = "${s.check}",\n        data = "${s.data}",\n    )`;

// Thresholds + FRAME (pepper) are generated so domain enum stays free of plain targets.
// Residual RE risk: FRAME still ships in binary; board/rewards stay ciphertext.
writeFileSync(
  ktPath,
  `package eu.kanade.domain.easteregg.lattice

/**
 * Generated by tools/lattice_forge.mjs — do not edit by hand.
 * Ciphertext only for board/rewards. FRAME + thresholds are required for Stage A
 * open-key derivation (scenario source of truth stays gitignored).
 */
internal object LatticeVaultData {
    const val VERSION = ${VERSION}

    /** Opaque frame fragment for Stage A canonical (not a player-facing secret). */
    const val FRAME = "${pepper.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"

    /** Latch thresholds for carriers in order: anime, manga, novel. */
    val THRESHOLDS = intArrayOf(${carriers.a}, ${carriers.m}, ${carriers.n})

    val STAGE_A = ${stageKt(stageA)}

    val STAGE_B = ${stageKt(stageB)}
}
`,
);
console.log('VERSION=' + VERSION);
console.log('STAGE_A key = ' + canonicalCarriers(carriers.a, carriers.m, carriers.n, pepper));
